name: Publish npm package

on: push

env:
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
    bump-version:
        name: "Bump Version on main"
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: "Checkout source code"
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
            - name: "cat package.json"
              run: cat ./package.json
            - name: "Automated Version Bump"
              id: version-bump
              uses: "phips28/gh-action-bump-version@master"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: "cat package.json"
              run: cat ./package.json
            - name: "Output Step"
              env:
                  NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
              run: echo "new tag $NEW_TAG"

    build-and-publish:
        name: Build and Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the branch
              uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  cache: pnpm
                  registry-url: https://registry.npmjs.org/
            - name: Install dependencies
              run: pnpm install
            - name: Build & publish the app
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
